# Site settings
title: tsunamusings
header-img: img/home-radio.jpg
email: tsunami643_at_gmail.com
description: "i play the dotes and think the dotes"
baseurl: "/blog"
url: "http://howdoiplay.com"
twitter_username: tsunami643
youtube_username: tsunami643

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
